package com.serverless.dbentity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.serverless.domain.InquiryState;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@DynamoDBTable(tableName = "PLACEHOLDER_INQUIRY_LIST_TABLE_NAME")
public class InquiryList {

    public static final String INQUIRY_LIST_TABLE_NAME = System.getenv("INQUIRY_LIST_TABLE_NAME");
    private String state; // should be set from InquiryList domain
    private String listId; // used to be UUID
    private int binTimeoutSeconds;
    private int itemProcessedCount;
    private int itemCount;
    private List<InquiryItem> inquiries; //todo ask rob if this should be saved

    @DynamoDBHashKey(attributeName = "listId")
    @DynamoDBAutoGeneratedKey
    public String getListId() { return listId; }
    public void setListId(String listId) { this.listId = listId; }

//    @DynamoDBRangeKey(attributeName = "itemProcessedCount")
    @DynamoDBAttribute(attributeName = "itemProcessedCount")
    public int getItemProcessedCount() { return itemProcessedCount; }
    public void setItemProcessedCount(int itemProcessedCount) { this.itemProcessedCount = itemProcessedCount; }

    @DynamoDBAttribute(attributeName = "state")
    public String getState() { return state; }
    public void setState(String state) { this.state = state; }

    // needed as the inquiry list will be empty when retrieving it from the DB
    @DynamoDBAttribute(attributeName = "itemCount")
    public int getItemCount() { return itemCount; }
    public void setItemCount(int itemCount) { this.itemCount = itemCount; }

    @DynamoDBIgnore //todo ask rob if this should be saved
    public int getBinTimeoutSeconds() { return binTimeoutSeconds; }
    public void setBinTimeoutSeconds(int binTimeoutSeconds) { this.binTimeoutSeconds = binTimeoutSeconds; }

    // this will mostly be empty, apart from the initial create call
    @DynamoDBIgnore //todo ask rob if this should be saved
    public List<InquiryItem> getInquiries() { return inquiries; }
    public void setInquiries(List<InquiryItem> inquiries) { this.inquiries = inquiries; }

    @Override
    public String toString() {
        return "InquiryList{" +
                "state='" + state + '\'' +
                ", listId='" + listId + '\'' +
                ", binTimeoutSeconds=" + binTimeoutSeconds +
                ", itemProcessedCount=" + itemProcessedCount +
                ", itemCount=" + itemCount +
                ", inquiries=" + inquiries +
                '}';
    }

}
