package com.serverless.dbentity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.ArrayList;

@DynamoDBTable(tableName = "PLACEHOLDER_INQUIRY_ITEM_TABLE_NAME")
public class InquiryItem {

    public static final String INQUIRY_ITEM_TABLE_NAME = System.getenv("INQUIRY_ITEM_TABLE_NAME");

    private String state; // should be set from InquiryState domain
    private String inquiryId; // used to be UUID
    private String listId; // used to be UUID
    private String instrumentName;
    private ArrayList<InquiryQuote> quotes;

    @DynamoDBHashKey(attributeName = "inquiryId")
    @DynamoDBAutoGeneratedKey
    public String getInquiryId() { return inquiryId; }
    public void setInquiryId(String inquiryId) { this.inquiryId = inquiryId; }

    @DynamoDBRangeKey(attributeName = "listId")
    public String getListId() { return listId; }
    public void setListId(String listId) { this.listId = listId; }

    @DynamoDBAttribute(attributeName = "state")
    public String getState() { return state; }
    public void setState(String state) { this.state = state; }

    @DynamoDBAttribute(attributeName = "instrumentName")
    public String getInstrumentName() { return instrumentName; }
    public void setInstrumentName(String instrumentName) { this.instrumentName = instrumentName; }

    @DynamoDBIgnore
    public ArrayList<InquiryQuote> getQuotes() { return quotes; }
    public void setQuotes(ArrayList<InquiryQuote> quotes) { this.quotes = quotes; }

    @Override
    public String toString() {
        return "InquiryItem{" +
                "state='" + state + '\'' +
                ", inquiryId='" + inquiryId + '\'' +
                ", listId='" + listId + '\'' +
                ", instrumentName='" + instrumentName + '\'' +
                ", quotes=" + quotes +
                '}';
    }
}
